spring:
  application:
    name: EDU-SERVICE
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/online_edu?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    appname: EDU-SERVICE
    prefer-ip-address: true
server:
  port: 8000
swagger2:
  enable: true
mybatis-plus:
  mapper-locations: classpath:com/atguigu/edu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
